// src/app/components/evento-card/evento-card.component.ts
import { Component, Input } from '@angular/core';
import { Evento } from '../../services/evento.service';
import { Router } from '@angular/router';

export interface EventoCard extends Evento {
  escudo1Url?: string;
  escudo2Url?: string;
}

@Component({
  selector: 'app-evento-card',
  templateUrl: './evento-card.component.html',
  styleUrls: ['./evento-card.component.css']
})
export class EventoCardComponent {
  @Input() evento!: EventoCard;

  constructor(private router: Router) {}

  irADetalle() {
    this.router.navigate(['/eventos', this.evento.id]);
  }
}

<div class="evento-card" (click)="irADetalle()">
  <div class="evento-nombre">{{ evento.nombre }}</div>
  <div class="evento-escudos">
    <img *ngIf="evento.escudo1Url" [src]="evento.escudo1Url" [alt]="evento.equipo1.nombre + ' escudo'" class="evento-escudo" />
    <span class="evento-vs">vs</span>
    <img *ngIf="evento.escudo2Url" [src]="evento.escudo2Url" [alt]="evento.equipo2.nombre + ' escudo'" class="evento-escudo" />
  </div>
</div>

// src/components/EventoCard/EventoCard.tsx
import React from 'react';
import './evento-card.component.css';

export interface EventoCardProps {
  evento: {
    nombre: string;
    escudo1Url?: string;
    escudo2Url?: string;
    equipo1: { nombre: string };
    equipo2: { nombre: string };
  };
}

const EventoCard: React.FC<EventoCardProps> = ({ evento }) => (
  <div className="evento-card">
    <div className="evento-nombre">{evento.nombre}</div>
    <div className="evento-escudos">
      {evento.escudo1Url && (
        <img src={evento.escudo1Url} alt={`${evento.equipo1.nombre} escudo`} className="evento-escudo" />
      )}
      <span className="evento-vs">vs</span>
      {evento.escudo2Url && (
        <img src={evento.escudo2Url} alt={`${evento.equipo2.nombre} escudo`} className="evento-escudo" />
      )}
    </div>
  </div>
);

export default EventoCard;
