// src/app/components/equipo-card/equipo-card.component.ts
import { Component, Input } from '@angular/core';
import { Equipo } from '../../services/equipo.service';
import { Router } from '@angular/router';

export interface EquipoCard extends Equipo {
  escudoUrl?: string;
  fondoUrl?: string;
}

@Component({
  selector: 'app-equipo-card',
  templateUrl: './equipo-card.component.html',
  styleUrls: ['./equipo-card.component.css']
})
export class EquipoCardComponent {
  @Input() equipo!: EquipoCard;

  constructor(private router: Router) {}

  onCardClick() {
    this.router.navigate(['/equipos', this.equipo.id]);
  }
}

<div class="equipo-card" (click)="onCardClick()">
  <div class="card-fondo">
    <img *ngIf="equipo.fondoUrl" [src]="equipo.fondoUrl" alt="Fondo estadio" class="fondo-blur" />
  </div>
  <div class="card-nombre-escudo">
    <div class="card-nombre">
      <span class="equipo-nombre">{{ equipo.nombre }}</span>
    </div>
    <img class="equipo-escudo" *ngIf="equipo.escudoUrl" [src]="equipo.escudoUrl" [alt]="equipo.nombre + ' escudo'" />
  </div>
</div>

// src/components/EquipoCard/EquipoCard.tsx
import React from 'react';
import './equipo-card.component.css';

export interface EquipoCardProps {
  equipo: {
    nombre: string;
    escudoUrl?: string;
    fondoUrl?: string;
  };
}

const EquipoCard: React.FC<EquipoCardProps> = ({ equipo }) => (
  <div className="equipo-card">
    <div className="card-fondo">
      {equipo.fondoUrl && (
        <img src={equipo.fondoUrl} alt="Fondo estadio" className="fondo-blur" />
      )}
    </div>
    <div className="card-nombre-escudo">
      <div className="card-nombre">
        <span className="equipo-nombre">{equipo.nombre}</span>
      </div>
      {equipo.escudoUrl && (
        <img className="equipo-escudo" src={equipo.escudoUrl} alt={`${equipo.nombre} escudo`} />
      )}
    </div>
  </div>
);

export default EquipoCard;
